image: denoland/deno:latest

stages:
  - check
  - build
  - docker

.install_node: &install_node
  - apt-get update && apt-get install -y --no-install-recommends nodejs
  - rm -rf /var/lib/apt/lists/*

lint:
  stage: check
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno task lint
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/

typecheck:
  stage: check
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno run -A npm:@inlang/paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide
    - deno task check
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/

build:
  stage: build
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno task build
  artifacts:
    paths:
      - build/
    expire_in: 1 week
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/

docker:
  stage: docker
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"auth\":\"$(echo -n $CI_REGISTRY_USER:$CI_REGISTRY_PASSWORD | base64 -w 0)\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
      --destination $CI_REGISTRY_IMAGE:latest
  only:
    - main
