image: denoland/deno:latest

stages:
  - check
  - build

.install_node: &install_node
  - apt-get update && apt-get install -y --no-install-recommends nodejs
  - rm -rf /var/lib/apt/lists/*

lint:
  stage: check
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno task lint
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/

typecheck:
  stage: check
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno run -A npm:@inlang/paraglide-js compile --project ./project.inlang --outdir ./src/lib/paraglide
    - deno task check
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/

build:
  stage: build
  script:
    - *install_node
    - deno install --frozen --allow-scripts
    - deno task build
  artifacts:
    paths:
      - .svelte-kit/cloudflare/
    expire_in: 1 week
  cache:
    key:
      files:
        - deno.lock
    paths:
      - node_modules/
      - /deno-dir/
