---
when:
  - event: push
    branch: main
  - event: manual

variables:
  - &ftp_env
    FTP_PASSWORD:
      from_secret: ftp_password

steps:
  - name: build
    image: oven/bun:alpine
    commands:
      - bun install --frozen-lockfile
      - bun run build

  - name: deploy
    image: alpine:latest
    environment:
      <<: *ftp_env
    commands:
      - apk add --no-cache lftp
      - lftp -c "open -u blossomos-website:$FTP_PASSWORD ftp://storage.bunnycdn.com; mirror -R --delete --verbose build/ /"
    depends_on: [build]
